# Generated by Django 5.2.6 on 2025-09-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mothly_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goal_target', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sip_investment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sip_rate', models.FloatField(default=12)),
                ('sip_year', models.IntegerField(default=1)),
            ],
        ),
    ]
