# Generated by Django 5.2.6 on 2025-09-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financedata',
            old_name='mothly_expense',
            new_name='monthly_expense',
        ),
        migrations.RenameField(
            model_name='financedata',
            old_name='sip_year',
            new_name='sip_years',
        ),
    ]
