# Generated by Django 5.2.6 on 2025-09-14 06:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_mothly_expense_financedata_monthly_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financedata',
            name='sip_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5),
        ),
    ]
